---
title: Kickboxing-lightweight ranking by the numbers
author: c1aud6io_hh
date: '2019-06-12'
slug: lightweight-ranking
categories:
  - kickboxing
tags: []
lastmod: '2019-06-12T19:23:18-04:00'
keywords: []
description: ''
comment: no
toc: no
autoCollapseToc: no
contentCopyright: no
reward: no
mathjax: no
---

<!--more-->


http://combatpress.com/2019/06/combat-press-kickboxing-rankings-june-2019/
```{r libraries, message=FALSE}
library(tidyverse)
library(vroom)
library(svDialogs)
library(readr)
library(janitor)
library(rvest)
library(ggthemes)
library(scales)
library(lubridate)
library(RSQLite)
library(fmsb)
library(purrr)
library(fmsb)
library(cowplot)
library(kableExtra)
library(knitr)
library(RColorBrewer)
library(forcats)
theme_set(theme_grey())
```


```{r read_wiki}
read_wiki <- function(name_f) {
  # get the vcard from wikipedia
  url <- paste0("https://en.m.wikipedia.org/wiki/", name_f)
  
  tokeep <-
    c(
      "name",
      "born",
      "nationality",
      "height",
      "stance",
      "total",
      "wins",
      "by_knockout",
      "losses",
      "by_knockout_2",
      "draws",
      "no_contests"
    )
  
  vcard <-
    url  %>%
    read_html() %>%
    html_nodes("table.infobox.vcard") %>%
    html_table(header = F) %>%
    data.frame() %>%
    rename(x = X1, value = X2) %>% {
      .$x[1] <- "name"
      .
    } %>%
    filter(x != "") %>%
    mutate(x = make_clean_names(x)) %>%
    filter(x %in% tokeep)  %>%
    spread(x, value)
  
  
  # table of records from wikipedia
  tb <-
    url %>%
    read_html() %>%
    html_nodes(".wikitable:not(.infobox.vcard)") %>%
    html_table(header = TRUE, fill = TRUE)
  
  if (length(tb) > 1)
    tb <-  tb[[1]] # select only first table
  
  tb_record <-
    tb %>%
    data.frame() %>%
    clean_names() %>%
    filter(!str_detect(date, "^[[:alpha:]]")) %>%
    mutate(date = ymd(date))
  
  # current winning streak
  curr_win <-
    tb_record %>%
    filter(result != "NC") %>% {
      # no contest is not a lost
      tibble(len =  rle(.$result)[[1]],
             result =  rle(.$result)[[2]])
    } %>%
    head(1) %>%
    mutate(cur_win = ifelse(result == "Win", len, 0))
  
  # max streak
  max_streak <-
    tibble(len =  rle(tb_record$result)[[1]],
           result =  rle(tb_record$result)[[2]])  %>%
    group_by(result) %>%
    summarize(len = max(len)) %>%
    mutate(result = paste0(result, "_streak")) %>%
    spread(result, len) %>%
    clean_names()
  
  cur_win <- curr_win$cur_win
  cbind(vcard, cur_win, max_streak)
}
```

```{r}
fighters <- c(
  "Marat Grigorian",
  "Sitthichai Sitsongpeenong",
  "Superbon Banchamek",
  "Giorgio Petrosyan",
  "Chingiz Allazov"
)

df <- map_dfr(fighters, read_wiki)



tab  <- 
  df %>% 
  mutate(born = as.numeric(str_extract(born, "[[:digit:]]{4}")), age = year(Sys.Date()) - born) %>% 
  separate(height, c("height_m", "height_f"), sep = "m") %>% 
  mutate(
    height_f = str_remove_all(height_f, "[:punct:]" ), 
    height_m = as.numeric(height_m),
    stance = replace_na(stance, "Orthodox")
  ) %>% 
  mutate_all(type.convert, as.is = TRUE) %>%  # numbers to numerics
  mutate_all(replace_na, 0) %>% 
  rename(KO_wins = by_knockout, KO_losses = by_knockout_2) %>% 
  mutate(color_f = brewer.pal(n = nrow(.), name = "Dark2")) %>% 
  separate(name, c("first_name", "last_name"), remove = FALSE) %>%
  mutate(ggname = paste0(first_name,"\n",last_name), rank = as.numeric(1:nrow(.))) %>% 
  mutate(ggname = fct_reorder(ggname, rank))  

# df2 <- 
#     tab %>% 
#     gather(metric, value, -c(contains("name"), nationality, color_f))

```
https://stackoverflow.com/questions/12904177/count-how-many-times-the-element-is-repeated-in-a-sequence-in-r

```{r age}
age <- 
  tab %>%
  ggplot(aes(ggname, age, fill = color_f)) +
  geom_col() +
  scale_fill_identity() +
  scale_y_continuous(breaks = 1:35,
                     labels = 1:35,
                     minor_breaks = NULL) +
  coord_cartesian(ylim = c(25, 35)) +
  labs(x = "", title = "Age", y = "years") +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", size = 10),
    axis.text.y = element_text(face = "bold", size = 10),
  )
```


```{r  height}
height <-
  tab %>%
  ggplot(aes(ggname, height_m, fill = color_f)) +
  geom_col() +
  scale_fill_identity() +
  labs(x = "", title = "Height", y = "meters") +
  coord_cartesian(ylim = c(1.73, 1.81)) +
  scale_y_continuous(
    breaks = seq(0, 1.85, 0.01),
    labels = seq(0, 1.85, 0.01),
    minor_breaks = NULL
  ) +
  geom_label(aes(y = height_m - 0.004,
                 label = height_f, ),
             # position = position_stack(vjust = .5),
             # label.padding = unit(0.1,"lines"),
             size = 3) +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    axis.text.x = element_text(face = "bold", size = 10),
    axis.text.y = element_text(face = "bold", size = 10),
  )
```
```{r}
perc_win <-
  tab %>%
  mutate(perc_win = wins/(total - no_contests)* 100) %>% 
    ggplot(aes(ggname, perc_win, fill = color_f)) +
    geom_col() +
    scale_fill_identity() +
    labs(x = "", title = "Percent wins", y = "") +
    coord_cartesian(ylim = c(70, 100)) +
    scale_y_continuous(
      breaks = seq(0, 100, 5),
      labels = paste0(seq(0, 100, 5), "%"),
      minor_breaks = NULL
    ) +
    geom_label(aes(y = perc_win - 4,
                 label = paste0("W: ", wins, "\n",
                                "L: ", losses, "\n",
                                "D: ", draws, "\n",
                                "NC: ", no_contests)
                 ),
             # position = position_stack(vjust = .5),
             # label.padding = unit(0.1,"lines"),
             size = 3) +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
    )
```

```{r win_streak}
  tab %>%
    ggplot(aes(ggname, cur_win, fill = color_f)) +
    geom_col() +
    scale_fill_identity() +
    labs(x = "", title = "Current Winning Streak", y = "") +
    scale_y_continuous(
      breaks = seq(0, 14, 2),
      labels = seq(0, 14, 2),
      # minor_breaks = NULL
    ) +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
    )
```


```{r}
  tab %>%
    ggplot(aes(ggname, win_streak, fill = color_f)) +
    geom_col() +
    scale_fill_identity() +
    labs(x = "", title = "Longest Winning Streak", y = "") +
    scale_y_continuous(
      breaks = seq(0, 28, 2),
      labels = seq(0, 28, 2),
      minor_breaks = NULL
    ) +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
    )
```

```{r KO_wins}
KO_wins <-
  tab %>%
  mutate(perc_KO = KO_wins/wins * 100) %>% 
    ggplot(aes(ggname, perc_KO, fill = color_f)) +
    geom_col() +
    scale_fill_identity() +
    labs(x = "", title = "Percent KO wins", y = "") +
    coord_cartesian(ylim = c(15, 70)) +
    scale_y_continuous(
      breaks = seq(0, 70, 10),
      labels = paste0(seq(0, 70, 10), "%"),
      # minor_breaks = NULL
    ) +
    geom_label(aes(y = perc_KO - 5,
                 label = paste0("KOs :", KO_wins,"\n",
                                "W: ", wins)
                 ),
             size = 3) +
    theme(
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      axis.text.x = element_text(face = "bold", size = 10),
      axis.text.y = element_text(face = "bold", size = 10),
    )
```

